services:
  - type: web
    name: pandit-services-clean
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PYTHON_VERSION
        value: 3.9
      - key: PATH
        value: $PATH:/opt/render/.local/bin
    autoDeploy: true
    repo: https://github.com/shivamwahi2000/pandit-services-clean.git
    branch: main